### ISSUE TITLE
"dyld: lazy symbol binding failed: Symbol not found"

### ISSUE THREAD

**Issue by polyominal** [rizsotto/Bear#389]
I'm working on macOS Mojave (10.14.6).
I tried to compile a single file using ``bear -- make A``, and it results in the following error:
```
$ bear -- make A
g++-11 -std=c++17 -O2 -Wall -Wextra -pedantic -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -Wno-unused-result -Wno-sign-conversion    A.cpp   -o A
dyld: lazy symbol binding failed: Symbol not found: __ZN6google8protobuf5EmptyC1EPNS0_5ArenaE
  Referenced from: /usr/local/Cellar/bear/3.0.12/libexec/bear/wrapper.d/as
  Expected in: /usr/local/opt/protobuf/lib/libprotobuf.28.dylib

dyld: Symbol not found: __ZN6google8protobuf5EmptyC1EPNS0_5ArenaE
  Referenced from: /usr/local/Cellar/bear/3.0.12/libexec/bear/wrapper.d/as
  Expected in: /usr/local/opt/protobuf/lib/libprotobuf.28.dylib

g++-11: internal compiler error: Abort trap: 6 signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [A] Error 4
clang: error: no such file or directory: '/var/folders/v1/q03_4mm946j_mn_2t7kv4zlh0000gn/T//ccy83D1m.s'
clang: error: no input file
```
My ``Makefile`` is as follows:
```
TARGET := A

CC = gcc-11
CXX = g++-11
CXXFLAGS := -std=c++17 -O2 -Wall -Wextra -pedantic -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -Wno-unused-result -Wno-sign-conversion

all: $(TARGET)
.PHONY: all
```
Another mac with 10.15.x also gave the exact same error, and everything seemed to be working fine on ubuntu under similar configuration.

**Comment by rizsotto** [comment]
Could you please answer the questions that is in the issue template? (Which version of Bear? How did you installed? etc...) Those are relevant info to understand to diagnose a problem like this.

It looks like a packaging problem to me. Your system has a different gRPC package installed, than the Bear was compiled and linked against... But that's just a guess at this point.

**Comment by rizsotto** [comment]
Thanks for the updates. This looks to me a library incompatibility issue. Could you please check the followings?

- What is the version of `grpc` package on your system?
- Was the `grpc` package in Homebrew recently updated?
- What version of `grpc` package `bear` was built against?
  - For this you need find the build logs of Homebrew.

If the two `grpc` versions are different, then you need to ask the package maintainers to rebuild. If the versions are the same, will re-open this ticket.

**Comment by FrankBro** [comment]
I have the same issue:

```
➜  brew install grpc
Warning: grpc 1.38.0 is already installed and up-to-date.
To reinstall 1.38.0, run:
  brew reinstall grpc
➜  brew install bear
Warning: bear 3.0.12 is already installed and up-to-date.
To reinstall 3.0.12, run:
  brew reinstall bear
```

And according to this https://formulae.brew.sh/formula/bear#default

That version of bear was built on that version of grpc.

Pretty much same setup as above.

**Comment by rizsotto** [comment]
Thanks @FrankBro , could you find the build log of Bear package? Or can you ask the package maintainer how the package were built? Or ask him/her to do a rebuild?

Missing symbol is usually a simptom of different library versions. Compiling and linking against grpc `1.38.0` works and [pass the tests](https://github.com/rizsotto/Bear/runs/2834561323?check_suite_focus=true). This is a packaging problem in my opinion.

**Comment by FrankBro** [comment]
I wonder if this is related but, trying to build Bear locally, I get this:

```
loading initial cache file /Users/frankbro/Bear/subprojects/tmp/BearSource/BearSource-cache-Release.cmake
-- Checking for modules 'protobuf;grpc++'
--   Package 'openssl', required by 'grpc', not found
```

What's weird is openssl is installed...

**Comment by rizsotto** [comment]
Yes, that's a weirdness of Homebrew handling multiple ssl libraries (or multiple version of the same library).

Please take a look to the CI workflow, [it shows](https://github.com/rizsotto/Bear/blob/master/.github/workflows/build_on_push.yml#L32) what needs to do to make CMake happy.
