### ISSUE TITLE
bear fails to build on OS X 10.7.5

### ISSUE THREAD

**Issue by breser** [rizsotto/Bear#46]
Linking C shared library libear.dylib
Undefined symbols for architecture x86_64:
  "_environ", referenced from:
      _bear_get_environ in environ.c.o
     (maybe you meant: _bear_get_environ, _bear_update_environ )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [src/libear.dylib] Error 1
make[1]: **\* [src/CMakeFiles/ear.dir/all] Error 2
make: **\* [all] Error 2
