### ISSUE TITLE
"AttributeError: 'list_iterator' object has no attribute 'next"

### ISSUE THREAD

**Issue by murraycu** [rizsotto/Bear#113]
Running Bear 2.1.2 (built from git and "make install"ed into /usr/local/bin) on my autotools-based glom project:
https://git.gnome.org/browse/glom
I see this python error at the end of the build:

...
  CXX      glom/utility_widgets/glom_glom-notebooklabelglom.o
  CXX      glom/navigation/glom_glom-box_tables.o
  CXXLD    glom/glom
  ITMRG  glom.desktop
make[2]: Leaving directory '/home/murrayc/checkout/gnome/glom'
make[1]: Leaving directory '/home/murrayc/checkout/gnome/glom'
bear: Something unexpected had happened.
Traceback (most recent call last):
  File "/usr/bin/bear", line 63, in main
    return capture(args)
  File "/usr/bin/bear", line 107, in capture
    json.dump(list(entries), handle, sort_keys=True, indent=4)
  File "/usr/bin/bear", line 90, in <genexpr>
    return (entry for entry in itertools.chain(previous, current)
  File "/usr/bin/bear", line 169, in format_entry
    atoms = classify_parameters(entry['command'])
  File "/usr/bin/bear", line 383, in classify_parameters
    args.next()
AttributeError: 'list_iterator' object has no attribute 'next'

**Comment by murraycu** [comment]
Sorry, I actually ran bear 2.1.0 (packaged in Ubuntu Linux 15.10). It works fine with bear 2.1.2.
